export interface Project {
  name: string;
  description: string;
  achievements?: string[];
}

export interface Experience {
  company: string;
  role: string;
  startDate: string;
  endDate: string;
  description?: string;
  projects?: Project[];
  technologies?: string[];
}

export const experiences: Experience[] = [
  {
    company: "Capgemini",
    role: "Senior Software Engineer",
    startDate: "2025-01",
    endDate: "Present",
    projects: [
      {
        name: "Email Response Bot",
        description:
          "Enterprise-grade system for automated email analysis leveraging Large Language Models (LLMs). " +
          "The solution analyzes incoming emails, enriches them with data from external systems, and generates " +
          "context-aware summaries and solution proposals to support customer-facing and operational teams.",
        achievements: [
          "Designed a scalable, event-driven architecture on AWS tailored for LLM-based workloads",
          "Implemented infrastructure as code using Terraform, ensuring repeatable and auditable deployments",
          "Built an API Gateway to ingest and validate incoming emails and trigger processing workflows",
          "Orchestrated multi-step workflows using AWS Step Functions for data retrieval, preprocessing, and LLM invocation",
          "Integrated external databases and Snowflake to enrich prompts with relevant business context",
          "Implemented Lambda-based services for data transformation and orchestration logic",
          "Collaborated on CI/CD pipelines using GitLab CI/CD to automate testing and deployments"
        ]
      }
    ],
    technologies: [
      "Python",
      "Terraform",
      "AWS (API Gateway, Step Functions, Lambda, SageMaker)",
      "Snowflake",
      "Git"
    ]
  },
  {
    company: "Capgemini",
    role: "Software Engineer",
    startDate: "2023-06",
    endDate: "2025-01",
    projects: [
      {
        name: "ADAS (Advanced Driver Assistance System)",
        description:
          "Large-scale enterprise system supporting validation and analysis of autonomous vehicle behavior. " +
          "The platform is used by multiple teams to process, validate, and analyze high-volume data generated by autonomous cars.",
        achievements: [
          "Participated in designing scalable AWS infrastructure capable of handling high-throughput data processing",
          "Developed and maintained CI/CD pipelines using GitLab CI/CD for automated builds, tests, and deployments",
          "Implemented GraphQL APIs with AWS AppSync to enable efficient and flexible data access for multiple consumers",
          "Built and optimized data processing jobs using AWS Glue and PySpark",
          "Developed and maintained Grafana dashboards to monitor system performance, data pipelines, and operational health",
          "Supported a large user base by troubleshooting complex system issues and improving system reliability",
          "Maintained architectural and operational documentation to support cross-team collaboration"
        ]
      },
      {
        name: "System for Forecasting Prices",
        description:
          "Cloud-based machine learning platform for forecasting car prices based on historical and client-provided data. " +
          "The system supports data preparation, model training, and inference workflows in collaboration with ML and data teams.",
        achievements: [
          "Collaborated closely with Data Architects and ML engineers to align data pipelines with model requirements",
          "Participated in designing AWS infrastructure using Terraform to support scalable ML workloads",
          "Prepared, cleaned, and preprocessed large datasets to enable accurate model training",
          "Implemented data storage and processing flows using S3, RDS, and Lambda-based services",
          "Ensured reproducibility and environment consistency across development and production environments"
        ]
      },
    ],
    technologies: [
      "Python",
      "PySpark",
      "Terraform",
      "AWS CDK",
      "AWS (Lambda, DynamoDB, AppSync, Glue, S3, Athena)",
      "Grafana",
      "Git"
    ]
  },
  {
    company: "Capgemini",
    role: "Software Engineer Intern",
    startDate: "2022-05",
    endDate: "2023-06",
    description:
      "Participated in a structured internship program focused on cloud platforms (AWS, GCP) and commercial software " +
      "development best practices, working under the guidance of senior engineers.",
    projects: [
      {
        name: "Enterprise Data Integration Project",
        description:
          "Enterprise data integration platform responsible for migrating large-scale on-premise data sources to AWS. " +
          "The solution enabled centralized data processing and analytics in the cloud.",
        achievements: [
          "Maintained and optimized ETL pipelines implemented with AWS Glue and Apache Spark",
          "Transformed and loaded large datasets into cloud-based analytical stores",
          "Improved job performance and stability through Spark tuning and monitoring",
          "Implemented and maintained infrastructure using Terraform, supporting multiple environments",
          "Collaborated with senior engineers to follow production-grade development and deployment practices"
        ]
      }
    ],
    technologies: [
      "Python",
      "PySpark",
      "Terraform",
      "AWS (Glue, Lambda, Step Functions, RDS, Athena)",
      "PostgreSQL",
      "Git"
    ]
  },
  {
    company: "Software Interactive",
    role: "Backend Developer Intern",
    startDate: "2022-03",
    endDate: "2022-04",
    projects: [
      {
        name: "Worker Reporter Tool",
        description:
          "Backend application developed from scratch to manage and report worker-related data. " +
          "The system exposed RESTful APIs consumed by a frontend application.",
        achievements: [
          "Designed REST APIs following best practices for resource modeling and versioning",
          "Designed relational database schema using PostgreSQL",
          "Developed CRUD operations using Django and Django REST Framework",
          "Used Git for version control and collaborative development"
        ]
      }
    ],
    technologies: [
      "Python",
      "Django",
      "Django REST Framework",
      "PostgreSQL",
      "Git"
    ]
  }
];
